baseURL: https://www.dsm-management-suite.de
languageCode: de-de
title: DSM Management Suite
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/Logo_XXS.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: DSM Management Suite
    # Hero subtitle (optional)
    subtitle: Open Source Patch Reporting Extension für Ivanti DSM - Softwareverteilung Windows
    # Button text
    buttontext: Mehr erfahren
    # Where the main hero button links to
    buttonlink: "#features"
    # Hero image (from static/images/___)
    image: illustrations/dsmneuerbenutzer.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /#features
  - title: Video
    url: /#video
  - title: Editionen
    url: /#editions
  - title: Demo
    url: /#demo
  - title: Sponsoring
    url: /#sponsoring
  - title: Hilfe
    sublinks:
    - title: Support
      url: /support
    - title: GitHub Issues
      url: https://github.com/MarcoGriep88/IvantiDSMManagementSuite/issues
  - title: Kontakt
    url: /#kontakt
  section1:
    title: Editionen
    subtitle: DSM Management Suite - Patch Management
    tiles:
    - title: Community Edition
      icon: mouse-globe
      text: Entwickelt und Supported von der Community auf GitHub. Support erfolgt über GitHub Issues.
      url: https://github.com/MarcoGriep88/IvantiDSMManagementSuite/
      buttonText: GitHub Repository
    - title: Patreon Edition
      icon: laptop-cloud
      text: Profitieren Sie vom zugriff auf das Unternehmensportal mit direktem Kontakt zum Entwickler, vorgefertigte virtuelle Appliances und Zugriff auf Feature-Umfragen. Ebenso können Sie Fragen stellen.
      url: https://patreon.com/griepmarco
      buttonText: Patreon Link
    - title: Cloud Edition
      icon: plug-cloud
      text: Managed Hosting in Frankfurt für die Web API und das Web Dashboard. Ich kümmere mich um das Hosting, Updates und Datensicherung.
      url: /#kontakt
      buttonText: Kontakt
  section2:
    title: Das bietet die DSM Management Suite
    subtitle: Die wichtigsten Features
    features:
    - title: Erweitertes Patch Management
      text: Ziehen Sie aussagekräftige Patch Reports aus Ihrer Umgebung. Identifizieren Sie welche Third-Party Applikation die meisten Lücken aufweist und wie effektiv tatsächlich Ihr Unternehmen geschützt ist.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Historische Daten
      text: DSM Management Suite zeigt Ihnen einen Patch Verlauf an mit dem Sie prognosen für die Zukunft erstellen können. Schließen Sie mehr Sicherheitslücken als hinzukommen?
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Manager Dashboard
      text: Das Windows Dashboard wie auch das Web Dashboard sind optimal für IT-Manager. Sie brauchen sich in keine komplizierte DSM-Konsole einzuarbeiten.
      icon: doc-sync
    - title: Mächtige Web API
      text: Alle Patch Management Daten sind über eine performante Web-API auswertbar. Nutzen Sie Ihre favorisierte Programmiersprache wie PowerShell oder Python um individuelle Reports oder Automatisierungsaufgaben zu entwickeln.
      icon: mobile-feed
  section3:
    title: Jetzt ein Video ansehen...
    subtitle: ...und sehen was die DSM Management Suite Ihnen bieten kann
    image: illustrations/mockups/app-mockup.png
    buttonText: Zum Video
    buttonLink: "#"
  section10:
      title: Jetzt Demo ansehen
      subtitle: Möchten Sie lieber selbst ausprobieren? Mit dem Demo Server haben Sie die Möglichkeit DSM Management Suite selbst auszuprobieren
      image: illustrations/mockups/app-mockup.png
      buttonText: Try the Demo
      buttonLink: "/demo"
  section4:
      title: Sponsoren
      subtitle: Werden Sie Sponsor indem Sie das Projekt über Patreon oder PayPal unterstützen.
      #clients:
      #  Brandmauer:
      #    quote: Möp
      #    name: Brandmauer IT
      #    job: Cheffe
  section5: true
  footer:
    # Social Media Title
    socialmediatitle: Social Media
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/MarcoGriep88
      icon: github
    - link: https://www.facebook.com/marco.griep.73
      icon: facebook
    - link: https://twitter.com/MarcoGriep
      icon: twitter
    - link: https://www.reddit.com/user/Fuzzybuzzjazz88
      icon: reddit
    bulmalogo: true
    quicklinks:
      column1:
        title: "Produkt"
        links:
        - text: Editionen vergleichen
          link: /#editions
        - text: Datenschutz
          link: /datenschutz
        - text: Impressum
          link: /impressum
        - text: Lizenz
          link: http://www.gnu.de/documents/gpl.de.html
      column2:
        title: "Dokumente"
        links:
        - text: Deutsche Anleitung
          link: https://www.marcogriep.de/blog/dsm-management-suite-anleitung/
        - text: English manual
          link: https://www.marcogriep.com/blog/dsm-management-suite-manual/
        - text: GitHub Repository
          link: https://github.com/MarcoGriep88/IvantiDSMManagementSuite
        - text: Patreon
          link: https://www.patreon.com/griepmarco
      column3:
        title: "Blogs"
        links:
        - text: Deutscher Entwickler Blog
          link: https://www.marcogriep.de/blog
        - text: English Developer Blog
          link: https://www.marcogriep.com/blog