// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Packless.Database;

namespace Packless.Migrations
{
    [DbContext(typeof(PacklessDbContext))]
    partial class PacklessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Packless.Models.PatchData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Compliance");

                    b.Property<string>("Computer");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("FixDate");

                    b.Property<DateTime>("FoundDate");

                    b.Property<string>("Patch");

                    b.HasKey("Id");

                    b.ToTable("PatchDataCollection");
                });

            modelBuilder.Entity("Packless.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
